apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-1vsw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-1vsw
    app.kubernetes.io/part-of: cin4s-839-0088-app
  name: devfile-sample-1vsw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-1vsw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-1vsw
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0088-tenant/cin4s-839-0088-app/devfile-sample-1vsw@sha256:ac92499cce5f916ed9a794d49ffa5695726def6d0bb85b3b676e2f9741fc038d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
